version: '3.8'
services:
  postgres:
    hostname: postgres
    container_name: dev-database
    restart: always
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fakedata
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - compose-bridge
  fastapi:
    container_name: apoenastack-api
    build: 
      context: ./apoena-api-fastapi
      dockerfile: Dockerfile
    environment:
      - ENV=dev
    ports:
      - "8080:8080"
    volumes:
      - ../:/app
    networks:
      - compose-bridge
networks:
  compose-bridge:
    driver: bridge
    